import type { NextPage } from 'next'
import Head from 'next/head'
import Grid from '@mui/material/Unstable_Grid2';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Arthief</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container spacing={2}>
            <Grid xs={1} sm={1} md={2} lg={2}></Grid>
            <Grid xs={10} sm={10} md={7} lg={7}>
                <h1>Welcome to Arthief!</h1>
            </Grid>
            <Grid xs={1} sm={1} md={3} lg={3}></Grid>
        </Grid>

    </div>
  )
}

export default Home
